In [52]:
import os
import numpy as np

dirname = os.path.abspath("./")
# fname = os.path.join(dirname,"practice9.txt")
# fid = open(fname, "r")
# fid.close()
# print(fid.closed)

mname = os.path.join(dirname, "socioeconomic.csv")
a = np.loadtxt(mname, delimiter=',')
print(a)

s

[[ 62.  86.  82.]
 [ 72.  76.  83.]
 [ 75.  92.  90.]
 [ 55.  90.  76.]
 [ 64.  86.  90.]
 [ 21.  84.  87.]
 [ 64.  93.  93.]
 [ 80. 100.  90.]
 [ 67.  87.  52.]
 [ 72.  86.  88.]
 [ 42.  74.  57.]
 [ 76.  98.  89.]
 [ 76.  97.  97.]
 [ 41.  84.  59.]
 [ 48.  91.  73.]
 [ 76.  34.  38.]
 [ 53.  45.  76.]
 [ 60.  56.  81.]
 [ 42.  44.  45.]
 [ 78.  82.  92.]
 [ 29.  72.  39.]
 [ 48.  55.  34.]
 [ 55.  71.  41.]
 [ 29.  50.  16.]
 [ 21.  23.  33.]
 [ 47.  39.  53.]
 [ 81.  28.  67.]
 [ 36.  32.  57.]
 [ 22.  22.  26.]
 [ 44.  25.  29.]
 [ 15.  29.  10.]
 [  7.   7.  15.]
 [ 42.  26.  19.]
 [  9.  19.  10.]
 [ 21.  15.  13.]
 [ 21.  20.  24.]
 [ 16.  26.  20.]
 [ 16.  28.   7.]
 [  9.  17.   3.]
 [ 14.  22.  16.]
 [ 12.  30.   6.]
 [ 17.  25.  11.]
 [  7.  20.   8.]
 [ 34.  47.  41.]
 [  8.  32.  10.]]
