In [1]:
pwd

'/Users/boomchawit/KyotoU/data_analysis_practice'

In [17]:
import numpy as np

a = np.random.randn(10,3)

x0 = a[:,0]
x1 = a[0,:]

x2 = a[:,1]
#c0,c1,c2,c3,c4,c5,c6,c7,c8,c9 = a
print(a)

print([cc for cc in a])

[[ 0.81991023 -1.81859613 -2.35768136]
 [ 0.49766023 -0.41506228 -0.39745377]
 [ 1.79959673  0.9465943  -0.03080868]
 [ 0.22585062 -1.72740324 -1.00122265]
 [-1.30379262  0.43472831  1.34712725]
 [-0.50963832 -0.37719949 -0.57644578]
 [ 0.05614536 -0.04399122 -0.86047655]
 [-1.68679734 -0.83404788 -0.63336219]
 [-0.15839844 -0.0155667   0.17345619]
 [-2.01731304 -0.13284191  0.16811258]]
[array([ 0.81991023, -1.81859613, -2.35768136]), array([ 0.49766023, -0.41506228, -0.39745377]), array([ 1.79959673,  0.9465943 , -0.03080868]), array([ 0.22585062, -1.72740324, -1.00122265]), array([-1.30379262,  0.43472831,  1.34712725]), array([-0.50963832, -0.37719949, -0.57644578]), array([ 0.05614536, -0.04399122, -0.86047655]), array([-1.68679734, -0.83404788, -0.63336219]), array([-0.15839844, -0.0155667 ,  0.17345619]), array([-2.01731304, -0.13284191,  0.16811258])]
