In [75]:
import numpy as np
np.random.seed(10)
a = np.random.randn(5,3)

fnameCSV = 'data10.csv'
np.savetxt(fnameCSV, a, delimiter = ',')
print(a)

[[ 1.3315865   0.71527897 -1.54540029]
 [-0.00838385  0.62133597 -0.72008556]
 [ 0.26551159  0.10854853  0.00429143]
 [-0.17460021  0.43302619  1.20303737]
 [-0.96506567  1.02827408  0.22863013]]


In [76]:
import csv

fnameCSV = 'data10-2.csv'

with open(fnameCSV,'w') as fid:
    writer = csv.writer(fid)
    writer.writerows(a)

In [77]:
with open(fnameCSV, 'w') as fid:
        writer = csv.writer(fid)
        for aa in a:
            writer.writerow(aa)

In [78]:
d = {'abc': 123, 'b':5, 'ccc': 'hello'}

# print(d['abc'], d['b'],d['ccc'])
# print()
# print(d.keys())

for key in d.keys():
    print(key,':',d[key])
    
for key,value in d.items():
    print(key,value)

abc : 123
b : 5
ccc : hello
abc 123
b 5
ccc hello


In [79]:
# d0 = dict(title='ABC123', artist = "Jackson 5")
# print(d0)
d0 = {'title' : 'ABC123', 'artist' : 'Jackson 5'}
d1 = dict(artist = 'U2', title = 'Lemon')
d2 = dict(artist = 'Blue Haerts', title = 'Linda Linda')

print(d0)
print(d1)
print(d2)

{'title': 'ABC123', 'artist': 'Jackson 5'}
{'artist': 'U2', 'title': 'Lemon'}
{'artist': 'Blue Haerts', 'title': 'Linda Linda'}


In [80]:
songs = [d0, d1, d2]

fnameCSV = 'data10-3.csv'
with open(fnameCSV, 'w') as fid:
    colnames = ['artist', 'title']
    writer = csv.DictWriter(fid,fieldnames = colnames)
    writer.writeheader()
    for d in songs:
        writer.writerow(d)

In [91]:
fnameCSV =  'data10-4.csv'

with open (fnameCSV, 'w') as fid:
    fid.write('artist,title \n')
    for d in songs:
        a = d['artist']
        t = d['title']
        fid.write(f"{a},{t}\n")